# Generated by Django 3.1.6 on 2021-02-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_projectdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileDetails',
            new_name='ClientDetail',
        ),
        migrations.RenameModel(
            old_name='ProjectDetails',
            new_name='ProjectDetail',
        ),
    ]
